### ISSUE TITLE
Units don't repair at the trade platform

### ISSUE THREAD

**Issue by Mailaender** [Mailaender/OpenHV#37]
They drive there, but nothing happens. Not sure why.

**Comment by GraionDilach** [comment]
Initially I thought this is because the Trade Platform has wrong footprint (should be `++ ++`, see https://github.com/OpenRA/OpenRA/pull/17141 why, your engine version includes this one already) but that alone just exposed another issue in upstream.

The current `Resupply` logic in OpenRA sets up a `nearEnough` value of 512 which is used as a maximum distance limit from the repair building's CenterPosition set here:
https://github.com/OpenRA/OpenRA/blob/23b3c237b7071fd308c4664b0b6c5d719c0f3c74/OpenRA.Mods.Common/Traits/Repairable.cs#L126

The problem is that this value is less than the half cell offset we need due to the Trade Platform's own 2x2 footprint, which prevents the units to occupy it's center and ending up with units going to repair never being able to reach the desired docking position. This doesn't affect OpenRA itself that heavily, since the repair pads included with the default games have an odd value of length atleast on one axis and the hardcoded 512 value is enough to cover one even axis already, and fails only with repair pads where the entire footprint is even.

![image](https://user-images.githubusercontent.com/1136302/72666998-98c61a80-3a17-11ea-9f09-ca4d0c6bab6d.png)
